spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tickets_db
        username: root
        password: admin2023
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 
        timeout: 5000
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
    thymeleaf:
        prefix: classpath:/templates/
